#!/bin/bash

cd /home/utena/domAutomation/Dom4GameServer/dom4server/
python manage.py checkname 2>&1 >> /home/utena/domAutomation/Dom4GameServer/dom4server/serverlogs/checkname.log
python processcommands.py checkname 2>&1 >> /home/utena/domAutomation/Dom4GameServer/dom4server/serverlogs/processcommands.log

